config/routes.rb
AcmApp::Application.routes.draw do

 

  resources :users do
    member do
      put "toggle_admin"
    end
  end
  resources :icpc_entries
  resources :projects
  
  resources :acm_projects, path: "showcase" do
    member do
      get "approve" # /showcase/:id/approve
    end
    collection do
      get "submissions" # /showcase/submissions
    end
  end

  get "/calendar/upcoming.json", to: "calendar_proxy#upcoming"
  get "/calendar/recent.json", to: "calendar_proxy#recent"

  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  post "/auth/failure", to: "pages#invalid_request"
  get "/signout", to: "sessions#destroy", as: "signout"

  root "pages#home"
  get "/invalid_request", to: 'pages#invalid_request'
  get "/calendar", to: "pages#calendar"
  get "/subscribe", to: "pages#subscribe"
  get "/admin", to: "pages#admin"

  get "/officers", to: "officers#officers_2017"
  get "/officers_index", to: "officers#officers_index"
  get "/officers_2015", to: "officers#officers_2015"
  get "/officers_2014", to: "officers#officers_2014"
  get "/officers_2013", to: "officers#officers_2013"
  
  get "tags/:tag", to: "projects#index", as: :tag

  get "/portfolio" => redirect("https://portfolio.wustl.edu/organization/acm"), as: :portfolio
  get "/twitter" => redirect("https://twitter.com/WashUACM"), as: :twitter
  get "/validator" => redirect("http://validator.w3.org/check?uri=https%3A%2F%2Facm.wustl.edu"), as: :validator

  get "/404", :to => "pages#not_found"

  

end

app/models/user.rb
class User < ActiveRecord::Base

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

	#relationships
	has_many :icpc_entries
	has_many :projects, foreign_key: "owner_id"
	
  before_create :set_defaults

  def self.from_omniauth(auth)
    uid_field = uid_field_from_provider auth[:provider]
    return nil if uid_field.nil?

    user = where({ uid_field => auth["uid"] }).first
    if user.nil?
      user = create_from_omniauth(auth)
    end
    return user
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|
      # Generic properties
      user.provider = auth["provider"]
      user.first_name = auth["info"]["first_name"]
      user.last_name = auth["info"]["last_name"]
      user.email = auth["info"]["email"]

      # Provider-specific properties
      case auth[:provider]
        when "open_id"
        when "google"
          user.open_id = auth["uid"]
        when "shibboleth"
          user.shib_uid = auth["uid"]
          user.shib_eppn = auth["extra"]["raw_info"]["eppn"]
          user.shib_affiliation = auth["extra"]["raw_info"]["affiliation"]
          user.shib_samaccountname = auth["extra"]["raw_info"]["sAMAccountName"]
          user.shib_credid = auth["extra"]["raw_info"]["wustlEduCredId"]
      end
    end
  end


  def self.uid_field_from_provider provider
    case provider
      when "google"
      return :open_id
      when "shibboleth"
      return :shib_uid
      else
      return nil
    end
  end

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end

  def is_admin?
    return self.role == "admin"
  end

  def is_admin= value
    self.role = value ? "admin" : ""
  end

  private
  def set_defaults
    self.personal_bio = "I am a member of WashU ACM."
  end

  def slug_candidates
    [
      :full_name,
      [:full_name, :created_at_year_month]
    ]
  end
  def created_at_year_month
    self.created_at.strftime("%b %Y")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  before_action :set_user, except: [:index]
  before_action :require_admin, only: [:index, :toggle_admin]
  before_action :require_permission, only: [:edit, :update, :destroy]
  
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit 
    @user = current_user
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1/toggle_admin
  def toggle_admin
    @user.is_admin = !@user.is_admin?
    @user.save!
    redirect_to @user
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    session[:user_id] = nil
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :personal_bio
      )
    end

    # Don't let users mess with each other's settings.
    def require_permission
      return permission_redirect unless @user == current_user or current_user.is_admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for current_user, :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
 
  <div class="control-group">
    <%= f.label :personal_bio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :personal_bio, :class => 'text_area', :rows => 4 %>
    </div>
  </div>
 
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to "Destroy User", user_path, :class => "btn btn-danger", confirm: "Are you sure?  All of your posts and projects will also be deleted.", method: "delete" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>User Settings <small><%= @user.full_name %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<h2>Users</h2>

<table class="table">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.full_name, user %></td>
    <td><%= user.email %></td>
    <td><%= user.role %></td>
  </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>

<h1>
  <%= @user.full_name %>
  <small><%= user_email_link(@user) %></small>
</h1>

<p class="lead">
  <%= @user.personal_bio %>
</p>

<% if @user == current_user %>
<p>
  Tip: To edit your personal bio (shown above), click <%= link_to "Settings", edit_user_path(@user) %>.
</p>
<% end %>

<% if @user.is_admin? %>
<p>
  This user is an administrator of the ACM web site.
</p>
<% end %>

<% if @user == current_user or current_user.is_admin? %>
<div class="form-actions">

  <% if current_user.is_admin? %>
  <%= link_to "Toggle Admin", toggle_admin_user_path(@user), :class => "btn", :method => "put" %>
  <% end %>

  <%= link_to "Settings", edit_user_path(@user), :class => "btn" %>
  <%= link_to "Sign Out", signout_path, class: "btn" %>
</div>
<% end %>