config/routes.rb
AcmApp::Application.routes.draw do

 

  resources :users do
    member do
      put "toggle_admin"
    end
  end
  resources :icpc_entries
  resources :projects
  
  resources :acm_projects, path: "showcase" do
    member do
      get "approve" # /showcase/:id/approve
    end
    collection do
      get "submissions" # /showcase/submissions
    end
  end

  get "/calendar/upcoming.json", to: "calendar_proxy#upcoming"
  get "/calendar/recent.json", to: "calendar_proxy#recent"

  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  post "/auth/failure", to: "pages#invalid_request"
  get "/signout", to: "sessions#destroy", as: "signout"

  root "pages#home"
  get "/invalid_request", to: 'pages#invalid_request'
  get "/calendar", to: "pages#calendar"
  get "/subscribe", to: "pages#subscribe"
  get "/admin", to: "pages#admin"

  get "/officers", to: "officers#officers_2017"
  get "/officers_index", to: "officers#officers_index"
  get "/officers_2015", to: "officers#officers_2015"
  get "/officers_2014", to: "officers#officers_2014"
  get "/officers_2013", to: "officers#officers_2013"
  
  get "tags/:tag", to: "projects#index", as: :tag

  get "/portfolio" => redirect("https://portfolio.wustl.edu/organization/acm"), as: :portfolio
  get "/twitter" => redirect("https://twitter.com/WashUACM"), as: :twitter
  get "/validator" => redirect("http://validator.w3.org/check?uri=https%3A%2F%2Facm.wustl.edu"), as: :validator

  get "/404", :to => "pages#not_found"

  

end

app/models/acm_project.rb
class AcmProject < ActiveRecord::Base

	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

	belongs_to :owner, class_name: "User"
	validates_presence_of :owner

	# Uploader functionality courtesy of carrierwave
	mount_uploader :image, ImageUploader

	validates_presence_of :name
	validates_presence_of :description

	after_initialize :init
	
	# simulated ENUM field in AcmProjects table
	validates_inclusion_of :status, :in => ["approved", "pending"]
	validates_presence_of :status
	def status
		read_attribute(:status)
	end
	def status= (value)
		write_attribute(:status, value)
	end

	def self.where_approved
		return self.where({ status: "approved" })
	end

	def self.where_pending
		return self.where({ status: "pending" })
	end

	private
	def init
		if self.status == "" || !self.status
			self.status = "pending"
		end
	end

	def slug_candidates
		[
			:name,
			[:name, :created_at_year_month]
		]
	end
	def created_at_year_month
		self.created_at.strftime("%b %Y")
	end

end

app/controllers/acm_projects_controller.rb
class AcmProjectsController < ApplicationController
	before_action :set_acm_project, only: [:show, :edit, :update, :destroy, :approve]
	before_action :require_login, except: [:index, :show]
	before_action :require_admin, except: [:index, :show, :new, :create]

	# GET /showcase
	# GET /showcase.json
	def index
		@acm_projects = AcmProject.where_approved.order(created_at: :desc)
	end

	# GET /showcase/1
	# GET /showcase/1.json
	def show
	end

	# GET /showcase/new
	def new
		@acm_project = AcmProject.new
	end

	# POST /showcase
	# POST /showcase.json
	def create
		@acm_project = AcmProject.new(acm_project_params)
		@acm_project.owner = current_user
		respond_to do |format|
			if @acm_project.save
				format.html { redirect_to @acm_project, notice: 'Your entry has been successfully submitted!' }
				format.json { render action: 'show', status: :created, location: @acm_project }
			else
				format.html { render action: 'new' }
				format.json { render json: @acm_project.errors, status: :unprocessable_entity }
			end
		end
	end

	def edit
	end

	# PATCH/PUT /showcase/1
	# PATCH/PUT /showcase/1.json
	def update
		respond_to do |format|
			if @acm_project.update(acm_project_params)
				format.html { redirect_to @acm_project, notice: 'Acm project was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @acm_project.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /showcase/1
	# DELETE /showcase/1.json
	def destroy
		@acm_project.destroy
		redirect_to submissions_acm_projects_path
	end

  def submissions
  	@acm_projects = AcmProject.all
  	@approved = AcmProject.where_approved
  	@pending = AcmProject.where_pending
  end

	def approve
		@acm_project.update_attribute(:status, "approved")
		redirect_to submissions_acm_projects_path
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_acm_project
		@acm_project = AcmProject.friendly.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def acm_project_params
		params.require(:acm_project).permit(
			:name,
			:description,
			:image
		)
	end
end

app/helpers/acm_projects_helper.rb
module AcmProjectsHelper
	def showcase_image_url(project)
		if project.image_url.nil?
			return "project-placeholder.png"
		else
			return project.image_url
		end
	end
end

app/views/acm_projects/_form.html.erb
<%= form_for @acm_project, url: acm_project_path(@acm_project), :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <% if @acm_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acm_project.errors.count, "error") %> prohibited this acm_project from being saved:</h2>

      <ul>
      <% @acm_project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  
   <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">     
      <%= f.text_area :description, :rows => 10, :class => 'wysihtml5' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>
   
  <div class="form-actions">
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                acm_projects_path, :class => 'btn' %>
    <%= f.submit "Submit", :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/acm_projects/_table.html.erb
<table class="table submissions">
	<thead>
		<tr>
			<th>Name</th>
			<th>Submitted by</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>

		<% acm_projects.each do |acm_project| %>
		<tr>
			<td><%= acm_project.name %></td>
			<td><%= acm_project.owner.full_name %></td>
			<td>
				<%= link_to 'Details', acm_project, :class => 'btn' %>
				<%= link_to 'Approve', approve_acm_project_path(acm_project), :class => 'btn' %>
				<%= link_to 'Edit', edit_acm_project_path(acm_project), :class => 'btn' %>
				<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
					acm_project,
					:method => 'delete',
					:data => { :confirm => 'Are you sure you want to permanently delete this entry?  There is now way of recovering it.' },
					:class => 'btn btn-danger'
				%>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/acm_projects/approve.html.erb
<h3>working...</h3>
<%= link_to 'Back', "/submissions" %>

app/views/acm_projects/edit.html.erb
<h1>Editing Showcase Project</h1>

<%= render 'form' %>

app/views/acm_projects/index.html.erb
<h1>ACM Showcase</h1>
<p class="lead">
  Welcome to the ACM Showcase.  This is where members of the ACM community can show off their work for current and future ACM members.
</p>

<% if current_user %>
<div class="text-center">
  <%= link_to "Submit Entry", new_acm_project_path, :class => "btn btn-primary" %>
</div>
<% else %>
<p class="lead">
  Simply sign in, submit a description of your work, and wait for it to be processed.
</p>
<% end %>



<% if @acm_projects != nil %>
<% @acm_projects.each do |acm_project| %>
<div class="project-holder">
  <div class="acm-project-header">
    <br/>
    <%= image_tag showcase_image_url(acm_project), class: "img-polaroid acm-project-image-header" %>
    <h3><%= acm_project.name %></h3>
    <p class="acm-project-submitted-by">
      Submitted by <%= acm_project.owner.full_name %>
    </p>
    <p class="acm-project-created-at">
      <%= acm_project.created_at.to_formatted_s(:month_day_year_words) %>
    </p>
  </div>
  <div class="project-description">
   <%= truncate(strip_tags(acm_project.description), length: 200) %>
   <%= link_to "Read more", acm_project %>
 </div>
</div>
<% end %>
<% end %>

app/views/acm_projects/new.html.erb
<div class="page-header">
	<h1>Submit to ACM Showcase</h1>
	<p class="lead">
		Use this form to submit your project to the ACM Showcase.
	</p>
	<p>
		<strong>Note:</strong> The ACM Showcase is for CSE students to show off their extracurricular projects.  If you are looking for ACM Project Matching, <%= link_to "click here", new_project_path %>.
	</p>
</div>

<%= render "form" %>

app/views/acm_projects/show.html.erb
<%- model_class = AcmProject -%>

<h2><%= @acm_project.name %></h2>

<div class="acm-project-floating-image">
	<%= image_tag showcase_image_url(@acm_project), class: "img-polaroid" %>
</div>

<div class="acm-project-description">
<%= markdown(@acm_project.description) %>
</div>

<!-- Deciding where to send users upon selection of 'back' buttton based on where they came from -->
<% if !request.referer.nil? && URI(request.referer).path == submissions_acm_projects_path %>
  <%= link_to 'Back', submissions_acm_projects_path %>
<% else  %>
  <%= link_to 'Back', acm_projects_path %>
<%end %>

app/views/acm_projects/submissions.html.erb
<h1> Submissions Dashboard </h1>
<p class="lead">
	Welcome to the Submissions Dashboard. Here admins can approve pending submissions and delete existing entries for the ACM showcase.
</p>


<% if @pending != nil %>
<h3>Awaiting Approval</h3>
<%= render partial: "table", locals: { acm_projects: @pending } %>
<% end %>

<% if @approved != nil %>
<h3>Previously Approved</h3>
<%= render partial: "table", locals: { acm_projects: @approved } %>
<% end %>