config/routes.rb
AcmApp::Application.routes.draw do

 

  resources :users do
    member do
      put "toggle_admin"
    end
  end
  resources :icpc_entries
  resources :projects
  
  resources :acm_projects, path: "showcase" do
    member do
      get "approve" # /showcase/:id/approve
    end
    collection do
      get "submissions" # /showcase/submissions
    end
  end

  get "/calendar/upcoming.json", to: "calendar_proxy#upcoming"
  get "/calendar/recent.json", to: "calendar_proxy#recent"

  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  post "/auth/failure", to: "pages#invalid_request"
  get "/signout", to: "sessions#destroy", as: "signout"

  root "pages#home"
  get "/invalid_request", to: 'pages#invalid_request'
  get "/calendar", to: "pages#calendar"
  get "/subscribe", to: "pages#subscribe"
  get "/admin", to: "pages#admin"

  get "/officers", to: "officers#officers_2017"
  get "/officers_index", to: "officers#officers_index"
  get "/officers_2015", to: "officers#officers_2015"
  get "/officers_2014", to: "officers#officers_2014"
  get "/officers_2013", to: "officers#officers_2013"
  
  get "tags/:tag", to: "projects#index", as: :tag

  get "/portfolio" => redirect("https://portfolio.wustl.edu/organization/acm"), as: :portfolio
  get "/twitter" => redirect("https://twitter.com/WashUACM"), as: :twitter
  get "/validator" => redirect("http://validator.w3.org/check?uri=https%3A%2F%2Facm.wustl.edu"), as: :validator

  get "/404", :to => "pages#not_found"

  

end

app/views/pages/admin.html.erb
<h2> Admin Tools </h2>

<%= link_to "Showcase Sumbissions", submissions_acm_projects_path %>

app/views/pages/calendar.html.erb
<h1>ACM Events</h1>

<p class="lead">Our full calendar is available on <a href="http://www.google.com/calendar/embed?src=su.wustl.edu_v3urbk68gh9g2g83db66su3erk%40group.calendar.google.com&ctz=America/Chicago">Google Calendar</a>.  You can use <a href="http://www.google.com/calendar/ical/su.wustl.edu_v3urbk68gh9g2g83db66su3erk%40group.calendar.google.com/public/basic.ics">this link (*.ics)</a> to import it into iCal or your favorite desktop calendar program.</p>

<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showDate=0&amp;showPrint=0&amp;showTz=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=su.wustl.edu_v3urbk68gh9g2g83db66su3erk%40group.calendar.google.com&amp;color=%23711616&amp;ctz=America%2FChicago" style=" border-width:0 " width="95%" height="600" frameborder="0" scrolling="no"></iframe>

app/views/pages/home.html.erb
<div  class="row">

	<!-- Welcome message -->
	<div class="span9">
		<div class="hero-unit">

			<h1>Welcome to WashU ACM.</h1>
			
			We are the student chapter of the <a href="http://www.acm.org">Association for Computing Machinery</a> at <a href="http://www.wustl.edu">Washington University in St. Louis</a>.  We sponsor coding challenges, presentations, colloquia, workshops, and social events in Computer Science and Engineering.  We're open to all students, whether or not you are majoring in CSE.  <%= link_to "Join us on Portfolio", portfolio_path %>, <%= link_to "subscribe to our mailing list", subscribe_path %>, and <%= link_to "follow us on Twitter", twitter_path %> to stay updated on the latest news and events from ACM.  Read below for just a few of the things that we do.
		</div>
		
	</div>
	
</div>

<div  class="row">
	<div class="span3">
		<h3>Project Matching</h3>
		<p class="lead">
			Helping WashU developers find ideas.
		</p>
		<p>
			Are you a CSE student looking for a cool project to make?  Are you someone with an idea looking for a CSE student to make it happen?
		</p>
		<p>
			Head over to <strong><%= link_to "ACM Project Matching", projects_path %></strong>.  This service connects students with great ideas with engineers who can make it a reality.  It's as easy as signing in, creating a profile, and posting a project.
		</p>
	</div>
	<div class="span3">
		<h3>ACM Tech Talks</h3>
		<p class="lead">
			The things you should know but no one ever told you.
		</p>
		<p>
			Ever wanted to know how to conquer a coding interview?  Or build an application in the cloud?  Or navigate your way through the depths of UNIX?  Ever wanted to learn about the cutting-edge research in our department?
		</p>
		<p>
			Join us for ACM Tech Talks.  <%= link_to "Subscribe to our mailing list", subscribe_path %> for announcements.
		</p>
	</div>
	<div class="span3">
		<h3>Coding Contests</h3>
		<p class="lead">
			Think you have what it takes to conquer the ICPC or the Google Code Jam?
		</p>
		<p>
			We send teams each year to the International Collegiate Programming Contest (ICPC) in November and the Google Code Jam in April.  Want to get involved?
		</p>
		<p>
			Watch out for announcements when we recruit our teams for the ICPC, and also take <%= link_to "CSE 232", "/cse232/" %>, offered every fall.  The skills you learn in CSE 232 will help you in technical interviews as well as in programming competitions!
		</p>
	</div>

</div>

app/views/pages/invalid_request.html.erb
<h2>Ooops!</h2>
<p>Something went wrong.</p>

app/views/pages/not_found.html.erb
<h2>404 Not Found</h2>

<p>The page you requested does not exist.  Please email us if you think this message is in error.</p>

app/views/pages/officers.html.erb
<h1>2014 ACM Officers</h1>

<p class="lead">Read below for a description of the people who make WashU ACM what it is today.</p>

<ul class="thumbnails">
	<li class="span3">
		<div class="thumbnail">
			<%= image_tag "officers/2014/shane.jpg", class: "img-rounded" %>
			<div class="caption">
				<h3>Shane Carr</h3>
				<p class="lead">President</p>
				<p>WashU ACM has a tradition of promoting a strong community with entirely student-run events in WashU Computer Science and Engineering.  As President, I want to continue this tradition and leave a legacy by helping WashU ACM develop strong patterns of innovation and programming for the student body.</p>
			</div>
		</div>
	</li>
	<li class="span3">
		<div class="thumbnail">
			<%= image_tag "officers/2014/alice.jpg", class: "img-rounded" %>
			<div class="caption">
				<h3>Alice Wang</h3>
				<p class="lead">Treasurer</p>
				<p>As the Treasurer and graphics designer of ACM, I hope to reach out to more students through increased fund raising and better PR.</p>
			</div>
		</div>
	</li>
	<li class="span3">
		<div class="thumbnail">
			<%= image_tag "officers/2014/aarthi.jpg", class: "img-rounded" %>
			<div class="caption">
				<h3>Aarthi Arunachalam</h3>
				<p class="lead">Publicity, VP</p>
				<p>Hi! I'm Aarthi, the VP and Publicity Director of ACM. I like hanging out with my friends, going on adventures, and playing with kittens! I also think it's awesome meeting new people and collaborating with other student groups, so if you have any fun ideas for ACM do with you or our group, let me know and we can make it happen!</p>
			</div>
		</div>
	</li>
	<li class="span3">
		<div class="thumbnail">
			<%= image_tag "officers/2014/brandon.jpg", class: "img-rounded" %>
			<div class="caption">
				<h3>Brandon Meeks</h3>
				<p class="lead">Technology Director</p>
				<p>I am very proud to be the Technology Director here at WashU ACM. It is my job to maintain the website and make sure all the ACM computers and equipment function properly. ACM has always been about teaching effective computer science practices, and I want to make sure we uphold and demonstrate the very skills we promote.</p>
			</div>
		</div>
	</li>
	<li class="span3">
		<div class="thumbnail">
			<%= image_tag "officers/2014/roger.jpg", class: "img-rounded" %>
			<div class="caption">
				<h3>Roger Iyengar</h3>
				<p class="lead">Activities</p>
				<p>Events are a huge part of the ACM. As Events Coordinator, my goal is to ensure that all events are both fun and educational for as many members as possible. I plan to maximize the benefit of attending ACM events by making sure they are run well. I will also put effort into scheduling and getting the word out about our events, so that attendance will be as high as possible.</p>
			</div>
		</div>
	</li>
	<li class="span3">
		<div class="thumbnail">
			<%= image_tag "officers/2014/jordan.jpg", class: "img-rounded" %>
			<div class="caption">
				<h3>Jordan Mecom</h3>
				<p class="lead">Liaison</p>
				<p>As Industry Liaison, my primary goal is to develop strong relationships between ACM and companies that computer science majors would be interesting in working for. ACM is focused on serving the WashU computer science student body, and professional development and industry exposure is an important part of that. </p>
			</div>
		</div>
	</li>
	<li class="span3">
		<div class="thumbnail">
			<div class="caption">
				<h3>Mark Dally</h3>
				<p class="lead">Historian</p>
			</div>
		</div>
	</li>
	<li class="span3">
		<div class="thumbnail">
			<div class="caption">
				<h3>Dr. Tao Ju</h3>
				<p class="lead">Advisor</p>
			</div>
		</div>
	</li>
</ul>

app/views/pages/subscribe.html.erb
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
    #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
    /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
       We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="http://wustl.us3.list-manage.com/subscribe/post?u=4cf8222d0c67a010da52d1183&amp;id=e5947d8009" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <h2>Subscribe to our mailing list</h2>
<div class="mc-field-group">
    <label for="mce-EMAIL">Email Address </label>
    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
    <label for="mce-FNAME">First Name </label>
    <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
    <label for="mce-LNAME">Last Name </label>
    <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group size1of2">
    <label for="mce-GRADYEAR">Graduation Year (if applicable) </label>
    <input type="number" name="GRADYEAR" class="" value="" id="mce-GRADYEAR">
</div>
<div class="mc-field-group">
    <label for="mce-MMERGE4">Affiliation </label>
    <select name="MMERGE4" class="" id="mce-MMERGE4">
    <option value=""></option>
    <option value="WashU Undergraduate Student">WashU Undergraduate Student</option>
<option value="WashU Graduate Student">WashU Graduate Student</option>
<option value="WashU Alum">WashU Alum</option>
<option value="WashU Faculty">WashU Faculty</option>
<option value="Industry Representative or Recruiter">Industry Representative or Recruiter</option>
<option value="Just someone interested in WashU ACM!">Just someone interested in WashU ACM!</option>

    </select>
</div>
<div class="mc-field-group input-group">
    <strong>In addition to an ACM newsletter, send info about… </strong>
    <ul><li><input type="checkbox" value="1" name="group[6845][1]" id="mce-group[6845]-6845-0"><label for="mce-group[6845]-6845-0">Code and Cookies (including ICPC)</label></li>
<li><input type="checkbox" value="2" name="group[6845][2]" id="mce-group[6845]-6845-1"><label for="mce-group[6845]-6845-1">Internship and Job Opportunities</label></li>
</ul>
</div>
    <div id="mce-responses" class="clear">
        <div class="response" id="mce-error-response" style="display:none"></div>
        <div class="response" id="mce-success-response" style="display:none"></div>
    </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_4cf8222d0c67a010da52d1183_e5947d8009" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>
<script type="text/javascript">
var fnames = new Array();var ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='GRADYEAR';ftypes[3]='number';fnames[4]='MMERGE4';ftypes[4]='dropdown';
try {
    var jqueryLoaded=jQuery;
    jqueryLoaded=true;
} catch(err) {
    var jqueryLoaded=false;
}
var head= document.getElementsByTagName('head')[0];
if (!jqueryLoaded) {
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = '//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js';
    head.appendChild(script);
    if (script.readyState && script.onload!==null){
        script.onreadystatechange= function () {
              if (this.readyState == 'complete') mce_preload_check();
        }    
    }
}

var err_style = '';
try{
    err_style = mc_custom_error_style;
} catch(e){
    err_style = '#mc_embed_signup input.mce_inline_error{border-color:#6B0505;} #mc_embed_signup div.mce_inline_error{margin: 0 0 1em 0; padding: 5px 10px; background-color:#6B0505; font-weight: bold; z-index: 1; color:#fff;}';
}
var head= document.getElementsByTagName('head')[0];
var style= document.createElement('style');
style.type= 'text/css';
if (style.styleSheet) {
  style.styleSheet.cssText = err_style;
} else {
  style.appendChild(document.createTextNode(err_style));
}
head.appendChild(style);
setTimeout('mce_preload_check();', 250);

var mce_preload_checks = 0;
function mce_preload_check(){
    if (mce_preload_checks>40) return;
    mce_preload_checks++;
    try {
        var jqueryLoaded=jQuery;
    } catch(err) {
        setTimeout('mce_preload_check();', 250);
        return;
    }
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = 'http://downloads.mailchimp.com/js/jquery.form-n-validate.js';
    head.appendChild(script);
    try {
        var validatorLoaded=jQuery("#fake-form").validate({});
    } catch(err) {
        setTimeout('mce_preload_check();', 250);
        return;
    }
    mce_init_form();
}
function mce_init_form(){
    jQuery(document).ready( function($) {
      var options = { errorClass: 'mce_inline_error', errorElement: 'div', onkeyup: function(){}, onfocusout:function(){}, onblur:function(){}  };
      var mce_validator = $("#mc-embedded-subscribe-form").validate(options);
      $("#mc-embedded-subscribe-form").unbind('submit');//remove the validator so we can get into beforeSubmit on the ajaxform, which then calls the validator
      options = { url: 'http://wustl.us3.list-manage1.com/subscribe/post-json?u=4cf8222d0c67a010da52d1183&id=e5947d8009&c=?', type: 'GET', dataType: 'json', contentType: "application/json; charset=utf-8",
                    beforeSubmit: function(){
                        $('#mce_tmp_error_msg').remove();
                        $('.datefield','#mc_embed_signup').each(
                            function(){
                                var txt = 'filled';
                                var fields = new Array();
                                var i = 0;
                                $(':text', this).each(
                                    function(){
                                        fields[i] = this;
                                        i++;
                                    });
                                $(':hidden', this).each(
                                    function(){
                                        var bday = false;
                                        if (fields.length == 2){
                                            bday = true;
                                            fields[2] = {'value':1970};//trick birthdays into having years
                                        }
                                        if ( fields[0].value=='MM' && fields[1].value=='DD' && (fields[2].value=='YYYY' || (bday && fields[2].value==1970) ) ){
                                            this.value = '';
                                        } else if ( fields[0].value=='' && fields[1].value=='' && (fields[2].value=='' || (bday && fields[2].value==1970) ) ){
                                            this.value = '';
                                        } else {
                                            if (/\[day\]/.test(fields[0].name)){
                                                this.value = fields[1].value+'/'+fields[0].value+'/'+fields[2].value;                                           
                                            } else {
                                                this.value = fields[0].value+'/'+fields[1].value+'/'+fields[2].value;
                                            }
                                        }
                                    });
                            });
                        $('.phonefield-us','#mc_embed_signup').each(
                            function(){
                                var fields = new Array();
                                var i = 0;
                                $(':text', this).each(
                                    function(){
                                        fields[i] = this;
                                        i++;
                                    });
                                $(':hidden', this).each(
                                    function(){
                                        if ( fields[0].value.length != 3 || fields[1].value.length!=3 || fields[2].value.length!=4 ){
                                            this.value = '';
                                        } else {
                                            this.value = 'filled';
                                        }
                                    });
                            });
                        return mce_validator.form();
                    }, 
                    success: mce_success_cb
                };
      $('#mc-embedded-subscribe-form').ajaxForm(options);
      
      
    });
}
function mce_success_cb(resp){
    $('#mce-success-response').hide();
    $('#mce-error-response').hide();
    if (resp.result=="success"){
        $('#mce-'+resp.result+'-response').show();
        $('#mce-'+resp.result+'-response').html(resp.msg);
        $('#mc-embedded-subscribe-form').each(function(){
            this.reset();
        });
    } else {
        var index = -1;
        var msg;
        try {
            var parts = resp.msg.split(' - ',2);
            if (parts[1]==undefined){
                msg = resp.msg;
            } else {
                i = parseInt(parts[0]);
                if (i.toString() == parts[0]){
                    index = parts[0];
                    msg = parts[1];
                } else {
                    index = -1;
                    msg = resp.msg;
                }
            }
        } catch(e){
            index = -1;
            msg = resp.msg;
        }
        try{
            if (index== -1){
                $('#mce-'+resp.result+'-response').show();
                $('#mce-'+resp.result+'-response').html(msg);            
            } else {
                err_id = 'mce_tmp_error_msg';
                html = '<div id="'+err_id+'" style="'+err_style+'"> '+msg+'</div>';
                
                var input_id = '#mc_embed_signup';
                var f = $(input_id);
                if (ftypes[index]=='address'){
                    input_id = '#mce-'+fnames[index]+'-addr1';
                    f = $(input_id).parent().parent().get(0);
                } else if (ftypes[index]=='date'){
                    input_id = '#mce-'+fnames[index]+'-month';
                    f = $(input_id).parent().parent().get(0);
                } else {
                    input_id = '#mce-'+fnames[index];
                    f = $().parent(input_id).get(0);
                }
                if (f){
                    $(f).append(html);
                    $(input_id).focus();
                } else {
                    $('#mce-'+resp.result+'-response').show();
                    $('#mce-'+resp.result+'-response').html(msg);
                }
            }
        } catch(e){
            $('#mce-'+resp.result+'-response').show();
            $('#mce-'+resp.result+'-response').html(msg);
        }
    }
}

</script>
<!--End mc_embed_signup-->