config/routes.rb
AcmApp::Application.routes.draw do

 

  resources :users do
    member do
      put "toggle_admin"
    end
  end
  resources :icpc_entries
  resources :projects
  
  resources :acm_projects, path: "showcase" do
    member do
      get "approve" # /showcase/:id/approve
    end
    collection do
      get "submissions" # /showcase/submissions
    end
  end

  get "/calendar/upcoming.json", to: "calendar_proxy#upcoming"
  get "/calendar/recent.json", to: "calendar_proxy#recent"

  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  post "/auth/failure", to: "pages#invalid_request"
  get "/signout", to: "sessions#destroy", as: "signout"

  root "pages#home"
  get "/invalid_request", to: 'pages#invalid_request'
  get "/calendar", to: "pages#calendar"
  get "/subscribe", to: "pages#subscribe"
  get "/admin", to: "pages#admin"

  get "/officers", to: "officers#officers_2017"
  get "/officers_index", to: "officers#officers_index"
  get "/officers_2015", to: "officers#officers_2015"
  get "/officers_2014", to: "officers#officers_2014"
  get "/officers_2013", to: "officers#officers_2013"
  
  get "tags/:tag", to: "projects#index", as: :tag

  get "/portfolio" => redirect("https://portfolio.wustl.edu/organization/acm"), as: :portfolio
  get "/twitter" => redirect("https://twitter.com/WashUACM"), as: :twitter
  get "/validator" => redirect("http://validator.w3.org/check?uri=https%3A%2F%2Facm.wustl.edu"), as: :validator

  get "/404", :to => "pages#not_found"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="We are the primary computer science organization at WashU. We sponsor Thursday Tech Talks, Code and Cookies, the ICPC, social events, and Project Matching." />
	<meta name="keywords" content="acm, amc, wustl, computer, technology, projects, t3, cnc" />

	<title><%= @title ? "#{@title} - " : "" %>WashU ACM</title>
	<%= favicon_link_tag "favicon.ico" %>
	
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<!--navigation -->
	<div class="navbar navbar-static-top">
		<div class="navbar-inner">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to image_tag("acm-grayscale.svg", id: "header-logo"), root_path %>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><%= link_to "Calendar", calendar_path %></li>
					<li><%= link_to "Projects", projects_path %></li>
					<li><%= link_to "Officers", officers_path %></li>
					<li><%= link_to "Showcase", acm_projects_path %></li>
					<% if current_user != nil and current_user.is_admin? %>
						<li><%= link_to "Admin Tools", admin_path %></li>
					<% end %>
				</ul>
				<div class="pull-right navbar-auth">
					<% if current_user %>
					<div class="navbar-username" >Welcome, <%= link_to current_user.first_name, current_user %>!</br>	
					</div>
					<% else %>
					Sign in with
					<%= link_to image_tag("wustlkey.png"), "/auth/shibboleth", title: "WUSTL Connect Login" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<!-- end navigation -->

	<div class="container">

		<!-- flash messages -->
		<%= custom_bootstrap_flash %>

		<div class="row">
			<div class="span9">
				<!-- content -->
				<%= yield %>
			</div>
			<div class="span3" id="sidebar">

				<%= link_to image_tag("washu-acm.svg", id: "sidebar-logo"), root_path %>

				<p id="sidebar-subscribe">
					<%= link_to "Subscribe to Mailing List \u00bb", subscribe_path %>
				</p>

				<div id="sidebar-events">
					<h3>Upcoming Events</h3>
					<div id="title-spacer"></div>
					<div id="sidebar-events-holder"></div>
					<script id="sidebar-event-template" type="text/x-handlebars-template">
						<div class="acm-sidebar-event">
							<h4 class="ase-name">
								<a href="{{url}}" target="_blank">{{name}}</a>
							</h4>
							<div class="ase-time">
								{{eventTime}}
							</div>
							<p class="ase-description">{{description}}</p>
						</div>
					</script>
				</div>
				<script type="text/javascript">
					window.sidebarEvents("sidebar-events-holder");
				</script>

				<%= link_to "Tweets by @WashUACM", twitter_path, class: "twitter-timeline", id: "sidebar-twitter", :"data-widget-id" => "424405968739237888" %>
				<script type="text/javascript">
					document.getElementById("sidebar-twitter").setAttribute("height", 400); // necessary to pass the validator
				</script>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?"http":"https";if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

				<div id="sidebar-seals">
					<%= image_tag "student-union.png" %>
					<%= image_tag "brookings-seal.svg" %>
				</div>

			</div>
		</div>
		<hr />
		<div class="row footer">
			<div class="span6">
				<p class="lead">
					Contact us at <span id="contact"></span>
					<script type="text/javascript">
						document.getElementById("contact").appendChild(window.acmAddr());
					</script>
				</p>
			</div>
			<div class="span3">
				<p>Web site designed by Brandon Meeks, Shane Carr and Han Liu.</p>
				<p>&copy; <span id="copyright-year"></span> WashU ACM</p>
				<script type="text/javascript">
					document.getElementById("copyright-year").appendChild(document.createTextNode(new Date().getFullYear()));
				</script>
			</div>
			<div class="span3">
				<%= link_to image_tag("html5.svg"), validator_path %>
				<img alt="Ssl_trust_logo" onclick="window.open('https://www.ssl.com/site_seals/48e5a768-52d9ccfe/site_report', 'site_report','height=500, width=400, top=100, left=100')" onmouseover="this.style.cursor='pointer'" src="https://www.ssl.com/images/ssl_trust_logo.gif" style="border: none;" />
			</div>
		</div>
	</div>
</body>
</html>